import React from "react";
import Footer from "./_common/footer";
import HeaderResponsive from "./_common/header";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "./firebase/service/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AuthProvider>
          <HeaderResponsive />
          {children}
          {/* <Footer /> */}
        </AuthProvider>
      </body>
    </html>
  );
}
